openapi: 3.0.3
info:
  title: Rokwire Rewards BB API
  description: Rewards Building Block API Documentation
  version: 1.0.8
servers:
  - url: 'https://api.rokwire.illinois.edu/rewards'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/rewards'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/rewards'
    description: Development server
  - url: 'http://localhost/rewards'
    description: Local server
tags:
  - name: Admin
    description: Clients administration applications APIs.
  - name: Internal
    description: Internal applications APIs.
  - name: Client
    description: Client applications APIs.
paths:
  /int/reward:
    post:
      tags:
        - Internal
      summary: Reward history
      description: |
        Reward history
      security:
        - bearerAuth: []
      requestBody:
        description: create Reward history
        content:
          application/json:
            schema:
              type: object
              properties:
                org_id:
                  type: string
                user_id:
                  type: string
                reward_type:
                  type: string
                code:
                  type: string
                building_block:
                  type: string
                description:
                  type: string
                date_created:
                  type: string
                date_updated:
                  type: string
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reward_type:
                      type: string
                    grantable_quantity:
                      type: integer
                    claimable_quantity:
                      type: integer
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /int/stats:
    get:
      tags:
        - Internal
      summary: Get Reward types
      description: |
        Get Reward types
      security:
        - bearerAuth: []
      requestBody:
        description: get Reward type
        content:
          application/json:
            schema:
              type: object
              properties:
                org_id:
                  type: string
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    org_id:
                      type: string
                    reward_type:
                      type: string
                    display_name:
                      type: string
                    active:
                      type: boolean
                    description:
                      type: string
                    date_created:
                      type: string
                    date_updated:
                      type: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /user/balance:
    get:
      tags:
        - Client
      summary: Retrieves balance for each user's wallet
      description: |
        Retrieves balance for each user's wallet
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reward_type:
                      type: string
                    amount:
                      type: integer
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /user/history:
    get: null
    tags:
      - Client
    summary: Retrieves the wallet history
    description: |
      Retrieves the wallet history
    security:
      - bearerAuth: []
    parameters:
      - name: reward_type
        in: query
        description: reward_type - filter by reward_type
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: code
        in: query
        description: code - filter by code
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: building_block
        in: query
        description: building_block - filter by building_block
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: limit
        in: query
        description: limit - limit the result
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: offset
        in: query
        description: offset
        required: true
        style: simple
        explode: false
        schema:
          type: integer
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  _id:
                    type: string
                  org_id:
                    type: string
                  user_id:
                    type: string
                  reward_type:
                    type: string
                  code:
                    type: string
                  building_block:
                    type: string
                  amount:
                    type: integer
                  description:
                    type: string
                  date_created:
                    type: string
                  date_updated:
                    type: string
      '400':
        description: Bad request
      '401':
        description: Unauthorized
      '500':
        description: Internal error
  /user/claims:
    get: null
    tags:
      - Client
    summary: Gets user claims
    description: |
      Gets user claims
    security:
      - bearerAuth: []
    parameters:
      - name: status
        in: query
        description: status
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: limit
        in: query
        description: limit - limit the result
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: offset
        in: query
        description: offset
        required: true
        style: simple
        explode: false
        schema:
          type: integer
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  _id:
                    type: string
                  org_id:
                    type: string
                  user_id:
                    type: string
                  items:
                    type: array
                    properties:
                      reward_type:
                        type: string
                      inventory_id:
                        type: string
                  status:
                    type: string
                  description:
                    type: string
                  date_created:
                    type: string
                  date_updated:
                    type: string
      '400':
        description: Bad request
      '401':
        description: Unauthorized
      '500':
        description: Internal error
    post:
      tags:
        - Client
      summary: Create a new claim user claim
      description: |
        Create a new claim user claim
      security:
        - bearerAuth: []
      requestBody:
        description: Create a new claim user claim
        content:
          application/json:
            schema:
              type: object
              properties:
                org_id:
                  type: string
                user_id:
                  type: string
                status:
                  type: string
                description:
                  type: string
                date_created:
                  type: string
                date_updated:
                  type: string
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1user~1claims/responses/200/content/application~1json/schema/items'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
