openapi: 3.0.3
info:
  title: Rokwire Rewards Building Block API
  description: Rewards Building Block API Documentation
  version: 1.0.8
servers:
  - url: 'https://api.rokwire.illinois.edu/rewards'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/rewards'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/rewards'
    description: Development server
  - url: 'http://localhost/rewards'
    description: Local server
tags:
  - name: Admin
    description: Clients administration applications APIs.
  - name: Internal
    description: Internal applications APIs.
  - name: Client
    description: Client applications APIs.
paths:
  /int/reward:
    post:
      tags:
        - Internal
      summary: Reward history
      description: |
        Reward history
      security:
        - bearerAuth: []
      requestBody:
        description: create Reward history
        content:
          application/json:
            schema:
              type: object
              properties:
                org_id:
                  type: string
                user_id:
                  type: string
                reward_type:
                  type: string
                code:
                  type: string
                building_block:
                  type: string
                description:
                  type: string
                date_created:
                  type: string
                date_updated:
                  type: string
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reward_type:
                      type: string
                    grantable_quantity:
                      type: integer
                    claimable_quantity:
                      type: integer
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /int/stats:
    get:
      tags:
        - Internal
      summary: Get Reward types
      description: |
        Get Reward types
      security:
        - bearerAuth: []
      requestBody:
        description: get Reward type
        content:
          application/json:
            schema:
              type: object
              properties:
                org_id:
                  type: string
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    org_id:
                      type: string
                    reward_type:
                      type: string
                    display_name:
                      type: string
                    active:
                      type: boolean
                    description:
                      type: string
                    date_created:
                      type: string
                    date_updated:
                      type: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /user/balance:
    get:
      tags:
        - Client
      summary: Retrieves balance for each user's wallet
      description: |
        Retrieves balance for each user's wallet
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reward_type:
                      type: string
                    amount:
                      type: integer
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
